name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Select option '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually occurred, include error messages
    validations:
      required: true

  - type: dropdown
    id: command
    attributes:
      label: Command Used
      description: Which StarterForge command were you using?
      options:
        - starterforge create
        - starterforge generate
        - starterforge web
        - starterforge list
        - npm run web
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration File
      description: If using a config file, please paste its contents
      placeholder: Paste your JSON configuration here (remove any sensitive data)
      render: json

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g. macOS 14.2, Windows 11, Ubuntu 22.04]
        - Node.js version: [e.g. 20.10.0]
        - StarterForge version: [e.g. 1.1.0]
        - Installation method: [npm global, local, etc.]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      placeholder: Paste error output here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, related issues, workarounds, etc.