name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details about your idea.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: One sentence describing the feature
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Framework/Technology Support
        - CLI Enhancement
        - Web Interface Improvement
        - New Project Type
        - Code Generation Enhancement
        - Documentation
        - Developer Experience
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Explain how you envision this feature working
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Other solutions or workarounds you've thought about

  - type: textarea
    id: examples
    attributes:
      label: Examples/Use Cases
      description: Provide concrete examples of how this feature would be used
      placeholder: |
        Example scenarios:
        1. User wants to...
        2. Developer needs to...

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - High - Blocking my workflow
        - Medium - Would significantly improve my experience
        - Low - Nice to have
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you interested in helping implement this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
        - label: I can help with testing/feedback
        - label: I can provide additional requirements/specifications

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the feature request
      placeholder: Links to similar features, mockups, technical considerations, etc.