name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Test CLI commands
      run: |
        node starterforge-cli.mjs --help
        node starterforge-cli.mjs list frameworks
        node starterforge-cli.mjs list types
        
    - name: Test config validation
      run: |
        echo '{"project_type": "web_app", "frontend": {"framework": "react"}, "backend": {"language": "node", "framework": "express"}, "database": {"engines": ["postgresql"]}, "auth": {"provider": "none"}}' > test-config.json
        node starterforge-cli.mjs generate test-config.json --mode scaffold-only
        rm test-config.json
        
    - name: Security audit
      run: npm audit --audit-level high
      continue-on-error: true