name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Verify package contents
      run: |
        npm pack --dry-run
        echo "Package contents verified"
        
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create release summary
      run: |
        echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
        echo "✅ Published StarterForge v${{ github.event.release.tag_name }} to npm" >> $GITHUB_STEP_SUMMARY
        echo "📦 Package: https://www.npmjs.com/package/starterforge" >> $GITHUB_STEP_SUMMARY
        echo "📋 Install: \`npm install -g starterforge\`" >> $GITHUB_STEP_SUMMARY